In [10]:
import pandas as pd
import plotly.express as px

## Reading the processed data

In [11]:
df = pd.read_csv("../data/processed_data.csv")
df.head(10)

    sales        date region
0  1638.0  2018-02-06  north
1  1647.0  2018-02-06  south
2  1731.0  2018-02-06   east
3  1557.0  2018-02-06   west
4  1587.0  2018-02-07  north
5  1698.0  2018-02-07  south
6  1542.0  2018-02-07   east
7  1635.0  2018-02-07   west
8  1602.0  2018-02-08  north
9  1536.0  2018-02-08  south

In [13]:
df.describe()

             sales
count  5880.000000
mean   1810.473299
std     283.015600
min    1500.000000
25%    1605.000000
50%    1704.000000
75%    2030.000000
max    2500.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5880 entries, 0 to 5879
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sales   5880 non-null   float64
 1   date    5880 non-null   object
 2   region  5880 non-null   object
dtypes: float64(1), object(2)
memory usage: 137.9+ KB

In [7]:
df.dtypes

sales     float64
date       object
region     object
dtype: object

In [9]:
print(f'Total NaN Values: {df.isna().sum().sum()}')
print(f'Total Null Values: {df.isnull().sum().sum()}')

Total NaN Values: 0
Total Null Values: 0

## Converting date column to appropriate data type

In our data, 'date' is an object data type. 
We convert it to datetime64 data type for better analysis

In [14]:
df['date'] = pd.to_datetime(df['date'])
df.dtypes

sales            float64
date      datetime64[ns]
region            object
dtype: object

## GROUPING BY & SORTING 

1. Grouping by date and then performing a summation on sales column will give us the exact sale figure happened on a particular day. 
2. As this is a time series data, we then sort the values by date

In [15]:
df = df.groupby("date")["sales"].sum().reset_index()
df = df.sort_values("date")
df.head(10)

        date   sales
0 2018-02-06  6573.0
1 2018-02-07  6462.0
2 2018-02-08  6342.0
3 2018-02-09  6717.0
4 2018-02-10  6543.0
5 2018-02-11  6468.0
6 2018-02-12  6588.0
7 2018-02-13  6786.0
8 2018-02-14  6687.0
9 2018-02-15  6618.0

## Visualization & Answering Business Problem

1. A line chart is plotted with 'date' as x-axis, 'sales' as y-axis in order to understand the trends over a particular time.
2. A vertical line is added on the exact business date requirement which is 15th of Jan, 2021 answering the question.

In [16]:
fig = px.line(df, x = "date", y="sales", title = "Sales Over Time")
fig.add_vline(x = "2021-01-15", line_dash = "dash", line_color = "red")
fig.show()

# Were sales higher before or after the Pink Morsel price increase on the 15th of January, 2021?

Answer: The sales grew after the pink morsel price increase as the chart clearly depicts.